### ISSUE TITLE
Tokens leaked

### ISSUE THREAD

**Issue by EJH2** [TheGreyDiamond/Jewel#1]
https://github.com/TheGreyDiamond/Jewel/blob/ff58b7f9a17f0643cb8917e489141dbd932706c7/client.py#L8
https://github.com/TheGreyDiamond/Jewel/blob/ff58b7f9a17f0643cb8917e489141dbd932706c7/client.py#L7

**Comment by TheGreyDiamond** [comment]
Oh now I know why my bot got hacked. Good thing I changed the tokens after that
